export const msg: string = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fringilla lectus nec ultrices tincidunt. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut tristique dictum sapien in viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum id vulputate diam. Curabitur et viverra turpis. Nullam vestibulum nibh lacus, vitae vehicula dolor interdum id. Nullam sodales pharetra tempor. Suspendisse potenti. Etiam vestibulum, turpis eu varius posuere, enim mauris dapibus leo, tincidunt euismod arcu nunc dapibus lacus. Pellentesque vel placerat sem, a posuere ante. Nulla facilisi. In id urna dictum velit fringilla imperdiet. Mauris tempor risus ac risus maximus, sit amet interdum massa accumsan. Sed porta feugiat faucibus. Praesent commodo sem ut felis aliquet placerat non feugiat dolor.

Pellentesque scelerisque varius massa in pretium. Ut egestas tempor eros, nec mollis nisl ultrices ac. Vivamus sit amet vulputate augue, vitae sagittis urna. Vestibulum sagittis sapien sed nisl eleifend molestie. Aenean auctor enim vitae ligula egestas convallis. Donec aliquam imperdiet scelerisque. Vestibulum ac orci vel tellus vehicula sagittis. Etiam varius orci a pharetra suscipit. Ut lorem lacus, consectetur in augue eu, sagittis imperdiet tortor. Donec malesuada faucibus nulla, eget ultricies turpis rhoncus eu. Duis auctor nisi ac augue feugiat, nec hendrerit nisl pulvinar. Sed convallis libero sit amet felis blandit, ullamcorper dictum orci auctor.

Ut euismod vitae sem vel accumsan. Morbi eu nibh posuere, eleifend nibh vitae, euismod sem. Nulla elementum maximus pulvinar. Donec mattis volutpat odio, non finibus tellus lacinia vel. Sed dictum nibh sed purus eleifend aliquam luctus vel dui. Maecenas at malesuada augue. Cras venenatis venenatis ex, a congue nisi fermentum eget. Etiam sapien elit, cursus eget pulvinar vitae, blandit ac sem. Nunc rutrum massa eget eros interdum tristique. Nunc in gravida ex, nec efficitur metus. Sed eget lectus interdum, malesuada mi eget, placerat sem. Vivamus vehicula at quam nec finibus.

Aenean nec ex vitae ex venenatis pharetra. Vestibulum vel vehicula ex, ut finibus metus. Suspendisse sed suscipit massa, eget lacinia mauris. Morbi interdum justo et justo bibendum tristique. Phasellus pretium, magna quis condimentum lobortis, massa libero hendrerit odio, in euismod quam sem et neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce pulvinar lacus sed odio laoreet malesuada. Vivamus vitae eleifend felis, et ornare quam. Sed elementum diam facilisis, sollicitudin quam a, egestas orci. Nullam est metus, faucibus non lorem a, maximus vulputate eros. Proin a porttitor ipsum. Nulla lobortis cursus aliquet.

In hendrerit, dui vitae mollis rutrum, turpis est finibus ligula, vitae eleifend ligula nunc et nisl. Aenean tempus dolor id mi tempus sagittis. Donec facilisis, arcu vel lobortis ullamcorper, nibh tortor sodales sapien, ut aliquet felis dui quis urna. Ut suscipit enim id erat congue, quis rhoncus nunc malesuada. Phasellus in velit sem. Donec a tellus venenatis, pharetra urna sed, hendrerit tortor. Vivamus consectetur nulla in leo lobortis, in finibus ante varius. Nullam porta elit molestie porta ultrices. Vestibulum auctor velit pretium felis semper interdum.

In sagittis diam in ante ultrices mattis. Vestibulum scelerisque lacus velit, id scelerisque mauris posuere id. Proin commodo ante sit amet enim vestibulum vestibulum. Curabitur a commodo quam. Sed et vehicula felis, ac rutrum libero. Pellentesque vitae ante gravida, facilisis lorem fermentum, gravida erat. Donec pretium sapien ac mollis feugiat.

Praesent mollis, leo vitae pretium auctor, felis libero vestibulum turpis, in finibus mi neque ut lacus. Cras pharetra mi at mattis egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc aliquam metus vel est congue, ac pellentesque diam imperdiet. Vivamus dapibus ipsum nibh, et faucibus velit sollicitudin vitae. Pellentesque mattis tempus est, in pretium est vulputate vitae. Duis sagittis, turpis et ullamcorper malesuada, nisl justo mattis nunc, et vehicula dui leo non nisi. In placerat pulvinar lacinia. Phasellus bibendum purus mi, a accumsan urna faucibus ac.

Sed velit massa, placerat et mi et, euismod efficitur justo. Vivamus porttitor velit non tempor scelerisque. In et dui ultricies, dignissim lectus ac, mollis purus. Donec cursus nisl id turpis iaculis ultricies. In non dolor eget justo congue sollicitudin. Maecenas placerat, diam vitae ultrices ullamcorper, mauris est dignissim risus, ac varius felis metus sed est. Aliquam hendrerit nisi odio, ac pulvinar dolor euismod vel. Aliquam tristique mollis eleifend. Proin vitae cursus enim. Vivamus rutrum, eros eu commodo scelerisque, felis mi vulputate augue, pretium viverra mauris metus vel nisi. Suspendisse in venenatis turpis. Sed accumsan sem sit amet elementum euismod. Sed cursus ultricies libero non congue. Vivamus sed quam vestibulum, venenatis mauris non, dapibus urna.

Nulla vitae hendrerit felis, at iaculis justo. Ut ac ullamcorper nulla. Pellentesque in mauris ultrices, lobortis eros vitae, elementum turpis. Duis laoreet tempus sapien at dignissim. Nunc vel aliquam nisl, in interdum risus. Integer lacus ipsum, iaculis ac nibh in, convallis mattis mi. Maecenas sodales dignissim mi nec eleifend. Cras pulvinar ut massa ac hendrerit. Vivamus rhoncus lobortis dapibus. Curabitur tempor ligula non ex ornare, in imperdiet ex mattis. Quisque cursus ex in ligula fermentum, eu luctus nibh blandit. Quisque aliquam, ex ac venenatis consectetur, eros velit condimentum dui, tristique pretium eros enim tempus mi. Proin rutrum felis nec tristique maximus. Nullam dapibus pellentesque fermentum. In volutpat ex vitae massa consectetur fringilla.

Cras odio diam, tincidunt in viverra ut, sollicitudin non risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam metus diam, auctor non est nec, gravida consectetur nisi. Cras leo dolor, tristique et tempus ac, aliquam sed ligula. Proin ex tellus, egestas ac volutpat ut, dictum semper justo. Quisque a dapibus leo, sed sollicitudin tortor. Sed et iaculis lacus.

Morbi posuere vulputate odio, interdum aliquam lectus egestas vel. Duis quis luctus arcu. Cras malesuada enim dictum augue iaculis convallis. Aliquam elementum lectus risus, id malesuada sapien pellentesque in. Quisque porta diam ut nibh ullamcorper, ac ornare sapien condimentum. Sed eu commodo mauris, eu ornare lorem. Curabitur mollis mi mauris, nec ornare enim finibus sed. Proin eget diam vitae turpis sagittis fringilla eu sit amet felis. Donec ac fermentum ante, ac interdum augue. Nunc sed massa auctor, suscipit nisi quis, maximus nunc. Suspendisse ut nunc vel erat ullamcorper mollis. Etiam vel vulputate magna. Donec libero nisl, lobortis ut leo ut, suscipit vulputate ante. Suspendisse egestas turpis mauris. Maecenas vehicula eros at ultricies porta. Donec tempus massa at dui laoreet placerat.

Maecenas vitae turpis varius, ornare eros ac, interdum ipsum. Curabitur urna dolor, volutpat ac neque non, condimentum rhoncus nulla. Integer vitae magna vel erat rutrum mollis sed id augue. Aliquam ac nisl ut eros ullamcorper tempor. Nullam et lacus tincidunt nunc condimentum bibendum eget a lacus. Curabitur laoreet dolor ac justo porta interdum. Nam lobortis pharetra tincidunt. Maecenas pulvinar ut velit vitae feugiat. Etiam porttitor finibus quam a interdum. Nulla venenatis eros nec justo tristique, sed elementum nisi ultrices. Proin imperdiet pretium felis.

Sed elit diam, auctor in placerat malesuada, efficitur at justo. Nullam sed lacus volutpat, finibus metus ut, mattis orci. Integer tempus eleifend facilisis. Nam posuere leo sit amet rutrum finibus. Donec id ipsum quam. Cras rutrum, nibh ac venenatis semper, diam diam pharetra nisl, at faucibus quam augue mattis nisl. Nulla elit urna, aliquam at orci in, porta efficitur libero. Ut ut mi rutrum nunc lobortis eleifend id ut felis. Sed ac libero vehicula, dapibus tortor at, vehicula sem. Maecenas nec dapibus lectus. Morbi vestibulum, urna non sollicitudin tempus, arcu magna lacinia mauris, vitae malesuada purus urna eu eros. Ut egestas ex quis lobortis consectetur. Maecenas eget facilisis ipsum, at finibus est. Etiam nec sem leo.

Quisque egestas orci sem, et cursus diam elementum nec. Curabitur non nunc at felis elementum lacinia. Fusce aliquam volutpat diam, non posuere metus rutrum ac. Nunc aliquet libero sodales lacus elementum maximus. Phasellus lacus lectus, varius id pretium bibendum, ultrices et arcu. Suspendisse ullamcorper lobortis purus, nec mollis lacus viverra sed. Curabitur elit erat, lacinia tempus erat id, pulvinar scelerisque enim. Aenean commodo ornare elementum. Sed convallis pellentesque sollicitudin. Etiam congue suscipit sapien eu dictum. Etiam consectetur, urna vitae cursus facilisis, nulla ligula pellentesque lorem, in suscipit ipsum purus sit amet lectus. Pellentesque convallis lectus ut neque vulputate, non finibus quam aliquam. Mauris a augue felis. Mauris faucibus luctus dictum.

Ut a condimentum quam. Phasellus vehicula mi nec libero feugiat, et sagittis eros hendrerit. Suspendisse ac nisi tempor, venenatis lectus vel, pellentesque elit. Aenean quis justo quam. Curabitur erat mi, congue in nunc vitae, luctus dapibus ligula. Duis nec ultrices felis, at euismod nisl. Quisque gravida, libero vel consequat lobortis, lectus diam sollicitudin lectus, non dapibus nibh lorem in lorem. Vestibulum rutrum turpis in ex ultrices, vitae tristique sapien interdum. Phasellus sapien metus, rhoncus vitae aliquam ac, pulvinar sed eros. Vestibulum mauris magna, ullamcorper vel ligula in, porttitor lacinia quam. In sodales pharetra maximus. Fusce viverra pellentesque quam ac fringilla. Donec vel aliquet libero. Vivamus urna nulla, dictum in dolor ac, ornare fermentum neque. Fusce rhoncus turpis molestie risus fermentum sollicitudin.

Morbi sed tellus velit. Morbi eget congue orci. Mauris interdum ultricies dui ac lobortis. Suspendisse id ornare erat. Nam commodo sem eu scelerisque blandit. Cras tincidunt quam finibus purus luctus, at scelerisque sapien accumsan. Pellentesque tincidunt commodo nunc, in dignissim dui placerat sed.

Phasellus vitae tellus ac nisi interdum interdum. Integer eleifend nulla tempor, hendrerit augue in, tempor lacus. Sed pellentesque libero et odio dapibus pulvinar. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed mauris neque, facilisis et sagittis quis, aliquam in metus. Nam libero lacus, dapibus a lacinia nec, aliquam sed elit. Vivamus sit amet urna pulvinar, pulvinar sem eu, pulvinar libero. Quisque at sodales turpis. Pellentesque sagittis laoreet ex vitae faucibus.

Vestibulum blandit venenatis dui eget dictum. Mauris sit amet finibus nisi, sed blandit ante. Suspendisse sed ante vel turpis luctus euismod ac at est. In sagittis purus dignissim mi tincidunt, mattis eleifend magna congue. Suspendisse a elit in tellus suscipit feugiat nec sed eros. Vestibulum at gravida metus. Nunc iaculis viverra enim eu imperdiet. Quisque molestie arcu ut rutrum finibus. Nunc pretium diam quis pretium hendrerit. Mauris rhoncus diam non volutpat convallis. Nulla semper iaculis vulputate. Nulla feugiat, nisi vel congue varius, tellus purus semper orci, in tincidunt nisi enim commodo mi. Aenean dolor ligula, sodales mollis nisl vel, sodales imperdiet velit. Nulla est ligula, tincidunt sit amet varius id, imperdiet lobortis sem. Aliquam at libero vestibulum, consectetur eros ac, rhoncus nulla. Sed ac finibus diam, vel auctor est.

Aliquam sed rhoncus velit. Quisque vestibulum, ex rhoncus posuere porttitor, massa nulla imperdiet nunc, eu lacinia erat ante vitae dui. Curabitur pulvinar nisi suscipit, luctus nisl eu, egestas diam. Aenean eget massa lectus. In accumsan turpis a sagittis malesuada. Nullam sit amet lacus aliquam, imperdiet mauris quis, sodales turpis. Duis lorem diam, fermentum eget dignissim at, egestas vel orci. Cras purus diam, luctus id laoreet vitae, tristique sed turpis.

Integer sollicitudin, nisi sed cursus scelerisque, magna dui consectetur eros, ut vehicula leo urna at libero. Aliquam vehicula turpis mi, sed viverra tortor porttitor in. Suspendisse eu tempor ligula. Nunc ligula purus, pulvinar sed dapibus nec, ultricies a risus. Duis ac eros est. Integer lobortis id quam in euismod. Quisque pulvinar, nulla eget viverra volutpat, velit odio luctus eros, at commodo odio velit et ligula. Praesent semper venenatis lacus non gravida. In vestibulum commodo facilisis. Nullam porttitor, lorem vel tincidunt feugiat, odio turpis finibus orci, et tincidunt lorem odio et ante. In tincidunt sapien varius, sollicitudin elit eu, sollicitudin metus.
`;
